import type { FoldedTree } from "./types";

// DPO sample — a folded objectives store, the same use-case as the design mock.
// Replaced by a live fetch of `/missions/:id/objectives` once auth is wired.
export const SAMPLE_TREE: FoldedTree = {
	overheadCostUsd: 0.2,
	orphanTasks: [],
	tasks: [],
	objectives: [
		{
			id: "OBJ-1",
			parent: null,
			title: "Q2 data-protection compliance",
			owner: "dpo-lead",
			status: "active",
			budgetUsd: 12,
			costUsd: 7.85,
			kpis: [
				{
					id: "K1",
					label: "ROPA completeness",
					owner: "dpo-lead",
					kind: "qualitative",
					source: "copilot-assessment",
					value: "partial",
					stale: false,
				},
				{
					id: "K3",
					label: "cost",
					owner: "dpo-lead",
					kind: "quantitative",
					source: "auto-stat",
					target: 12,
					unit: "USD",
					value: 7.85,
					stale: false,
				},
			],
			tasks: [],
			children: [
				{
					id: "OBJ-1.1",
					parent: "OBJ-1",
					title: "Update ROPA register",
					owner: "records-officer",
					status: "active",
					budgetUsd: 4,
					costUsd: 2.9,
					kpis: [
						{
							id: "K4",
							label: "records reconciled",
							owner: "records-officer",
							kind: "quantitative",
							source: "agent-reported",
							target: 50,
							value: 38,
							stale: true,
						},
					],
					tasks: [
						{
							id: "TASK-001",
							objective: "OBJ-1.1",
							title: "Inventory new processing activities",
							assignee: "records-officer",
							status: "in-progress",
							costUsd: 1.4,
							budgetUsd: 1.5,
						},
						{
							id: "TASK-002",
							objective: "OBJ-1.1",
							title: "Reconcile vendor / processor list",
							assignee: "records-officer",
							status: "completed",
							costUsd: 1.1,
							budgetUsd: 1,
						},
						{
							id: "TASK-003",
							objective: "OBJ-1.1",
							title: "Confirm retention periods",
							assignee: "records-officer",
							status: "blocked",
							costUsd: 0.4,
							budgetUsd: 1,
						},
					],
					children: [],
				},
				{
					id: "OBJ-1.2",
					parent: "OBJ-1",
					title: "DPIA for new CRM",
					owner: "assessor",
					status: "active",
					budgetUsd: 5,
					costUsd: 3.2,
					kpis: [
						{
							id: "K5",
							label: "risk register",
							owner: "assessor",
							kind: "qualitative",
							source: "copilot-assessment",
							value: "pending",
							stale: true,
						},
					],
					tasks: [
						{
							id: "TASK-010",
							objective: "OBJ-1.2",
							title: "Map CRM data flows",
							assignee: "assessor",
							status: "completed",
							costUsd: 1.6,
							budgetUsd: 1.5,
						},
						{
							id: "TASK-011",
							objective: "OBJ-1.2",
							title: "Risk scoring",
							assignee: "assessor",
							status: "in-progress",
							costUsd: 1.6,
							budgetUsd: 2,
						},
						{
							id: "TASK-012",
							objective: "OBJ-1.2",
							title: "Mitigation plan",
							assignee: "assessor",
							status: "open",
							costUsd: 0,
							budgetUsd: 1.5,
						},
					],
					children: [],
				},
			],
		},
		{
			id: "OBJ-2",
			parent: null,
			title: "Incident INC-2026-014 response",
			owner: "dpo-lead",
			status: "active",
			budgetUsd: 6,
			costUsd: 2.1,
			kpis: [
				{
					id: "K6",
					label: "notify deadline",
					owner: "dpo-lead",
					kind: "quantitative",
					source: "manual",
					value: "41h left",
					stale: false,
				},
				{
					id: "K7",
					label: "scope confirmed",
					owner: "records-officer",
					kind: "qualitative",
					source: "agent-reported",
					value: "pending",
					stale: true,
				},
			],
			tasks: [],
			children: [
				{
					id: "OBJ-2.1",
					parent: "OBJ-2",
					title: "Establish breach scope",
					owner: "records-officer",
					status: "active",
					budgetUsd: 3,
					costUsd: 1.3,
					kpis: [],
					tasks: [
						{
							id: "TASK-021",
							objective: "OBJ-2.1",
							title: "Pull & review access logs",
							assignee: "records-officer",
							status: "in-progress",
							costUsd: 1.3,
							budgetUsd: 1.5,
						},
					],
					children: [],
				},
			],
		},
	],
};
